In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('datasets/Advertising.csv')

In [3]:
df

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
1     44.5   39.3       45.1   10.4
2     17.2   45.9       69.3    9.3
3    151.5   41.3       58.5   18.5
4    180.8   10.8       58.4   12.9
..     ...    ...        ...    ...
195   38.2    3.7       13.8    7.6
196   94.2    4.9        8.1    9.7
197  177.0    9.3        6.4   12.8
198  283.6   42.0       66.2   25.5
199  232.1    8.6        8.7   13.4

[200 rows x 4 columns]

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 200 entries, 0 to 199
Data columns (total 4 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   TV         200 non-null    float64
 1   radio      200 non-null    float64
 2   newspaper  200 non-null    float64
 3   sales      200 non-null    float64
dtypes: float64(4)
memory usage: 6.4 KB


In [5]:
df.describe()

TV       radio   newspaper       sales
count  200.000000  200.000000  200.000000  200.000000
mean   147.042500   23.264000   30.554000   14.022500
std     85.854236   14.846809   21.778621    5.217457
min      0.700000    0.000000    0.300000    1.600000
25%     74.375000    9.975000   12.750000   10.375000
50%    149.750000   22.900000   25.750000   12.900000
75%    218.825000   36.525000   45.100000   17.400000
max    296.400000   49.600000  114.000000   27.000000

In [6]:
X = df.drop(columns=['sales'])

In [7]:
y= df['sales']

In [8]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

In [9]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X_train)
scaled_X_train = scaler.transform(X_train)
scaled_X_test = scaler.transform(X_test)

In [10]:
from sklearn.linear_model import Ridge
model = Ridge(alpha=100)

ridge = model.fit(X_train,y_train)

In [11]:
y_pred = ridge.predict(X_test)

In [12]:
from sklearn.metrics import mean_absolute_error

# Cross Validation

In [13]:
X = df.drop(columns=['sales'])
y= df['sales']

from sklearn.model_selection import train_test_split
#X_train,X_test,y_train,y_test = train_test_split(X,y,test_size=0.2,random_state=1)

from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
scaler.fit(X)
scaled_X = scaler.transform(X)


In [14]:
scaled_X

array([[ 9.69852266e-01,  9.81522472e-01,  1.77894547e+00],
       [-1.19737623e+00,  1.08280781e+00,  6.69578760e-01],
       [-1.51615499e+00,  1.52846331e+00,  1.78354865e+00],
       [ 5.20496822e-02,  1.21785493e+00,  1.28640506e+00],
       [ 3.94182198e-01, -8.41613655e-01,  1.28180188e+00],
       [-1.61540845e+00,  1.73103399e+00,  2.04592999e+00],
       [-1.04557682e+00,  6.43904671e-01, -3.24708413e-01],
       [-3.13436589e-01, -2.47406325e-01, -8.72486994e-01],
       [-1.61657614e+00, -1.42906863e+00, -1.36042422e+00],
       [ 6.16042873e-01, -1.39530685e+00, -4.30581584e-01],
       [-9.45155670e-01, -1.17923146e+00, -2.92486143e-01],
       [ 7.90028350e-01,  4.96973404e-02, -1.22232878e+00],
       [-1.43908760e+00,  7.99208859e-01,  1.62704048e+00],
       [-5.78501712e-01, -1.05768905e+00, -1.07502697e+00],
       [ 6.66253447e-01,  6.50657027e-01,  7.11007392e-01],
       [ 5.64664612e-01,  1.65000572e+00,  1.02862691e+00],
       [-9.25304978e-01,  9.00494200e-01

In [15]:
model = Ridge(alpha=100)

In [16]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=5, shuffle=True, random_state=1)




scores=[]

for train_index, test_index in kf.split(scaled_X) :
    X_train, X_test= scaled_X[train_index],scaled_X[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]
    
    # fit model
    
    model.fit(X_train,y_train)
    score = model.score(X_test, y_test)
    scores.append(score)

In [17]:
list(kf.split(scaled_X))

[(array([  0,   1,   2,   3,   5,   6,   7,   8,   9,  10,  12,  13,  14,
          15,  17,  19,  20,  21,  22,  23,  24,  25,  26,  30,  32,  33,
          36,  37,  39,  41,  42,  43,  45,  46,  48,  49,  50,  52,  53,
          54,  55,  56,  57,  60,  61,  62,  63,  64,  65,  66,  67,  68,
          70,  71,  72,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  90,  91,  92,  93,  96,  98,  99, 100,
         101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115,
         116, 117, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
         130, 131, 132, 133, 134, 135, 137, 138, 139, 140, 141, 142, 143,
         144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
         157, 158, 160, 161, 163, 164, 166, 167, 169, 170, 173, 175, 178,
         179, 180, 181, 182, 183, 185, 186, 187, 188, 189, 190, 191, 192,
         195, 196, 197, 199]),
  array([  4,  11,  16,  18,  27,  28,  29,  31,  34,  35,  38,  40,  44,
       

In [18]:
scaled_X[(np.array([  0,   1,   2,   3,   5,   6,   7,   8,   9,  10,  12,  13,  14,
          15,  17,  19,  20,  21,  22,  23,  24,  25,  26,  30,  32,  33,
          36,  37,  39,  41,  42,  43,  45,  46,  48,  49,  50,  52,  53,
          54,  55,  56,  57,  60,  61,  62,  63,  64,  65,  66,  67,  68,
          70,  71,  72,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,
          84,  85,  86,  87,  88,  90,  91,  92,  93,  96,  98,  99, 100,
         101, 103, 104, 105, 106, 107, 108, 109, 111, 112, 113, 114, 115,
         116, 117, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
         130, 131, 132, 133, 134, 135, 137, 138, 139, 140, 141, 142, 143,
         144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155, 156,
         157, 158, 160, 161, 163, 164, 166, 167, 169, 170, 173, 175, 178,
         179, 180, 181, 182, 183, 185, 186, 187, 188, 189, 190, 191, 192,
         195, 196, 197, 199]))]

array([[ 9.69852266e-01,  9.81522472e-01,  1.77894547e+00],
       [-1.19737623e+00,  1.08280781e+00,  6.69578760e-01],
       [-1.51615499e+00,  1.52846331e+00,  1.78354865e+00],
       [ 5.20496822e-02,  1.21785493e+00,  1.28640506e+00],
       [-1.61540845e+00,  1.73103399e+00,  2.04592999e+00],
       [-1.04557682e+00,  6.43904671e-01, -3.24708413e-01],
       [-3.13436589e-01, -2.47406325e-01, -8.72486994e-01],
       [-1.61657614e+00, -1.42906863e+00, -1.36042422e+00],
       [ 6.16042873e-01, -1.39530685e+00, -4.30581584e-01],
       [-9.45155670e-01, -1.17923146e+00, -2.92486143e-01],
       [-1.43908760e+00,  7.99208859e-01,  1.62704048e+00],
       [-5.78501712e-01, -1.05768905e+00, -1.07502697e+00],
       [ 6.66253447e-01,  6.50657027e-01,  7.11007392e-01],
       [ 5.64664612e-01,  1.65000572e+00,  1.02862691e+00],
       [ 1.56887609e+00,  1.10306488e+00,  1.16211917e+00],
       [ 3.00679600e-03,  4.29449843e-02, -5.27248393e-01],
       [ 8.33232798e-01,  2.99534513e-01

In [20]:
scores

[0.7614051087578547,
 0.750750544038752,
 0.6820282615537709,
 0.7992873813917032,
 0.796040156453441]

In [21]:
min_score_index=scores.index(min(scores))
min_score_index

2

In [24]:
# below to analyse the why test score at index 3 is low compare to other
# the below helps to undestand with the test data

In [22]:

fold_indices=list(kf.split(scaled_X))

train_index,test_index  =    fold_indices[min_score_index]

df_min_score_test=df.iloc[test_index]

In [23]:
df_min_score_test

TV  radio  newspaper  sales
0    230.1   37.8       69.2   22.1
2     17.2   45.9       69.3    9.3
6     57.5   32.8       23.5   11.8
13    97.5    7.6        7.2    9.7
21   237.4    5.1       23.5   12.5
36   266.9   43.8        5.0   25.4
45   175.1   22.5       31.5   14.9
46    89.7    9.9       35.7   10.6
55   198.9   49.4       60.0   23.7
62   239.3   15.5       27.3   15.7
65    69.0    9.3        0.9    9.3
70   199.1   30.6       38.7   18.3
75    16.9   43.7       89.4    8.7
77   120.5   28.5       14.2   14.2
81   239.8    4.1       36.9   12.3
82    75.3   20.3       32.5   11.3
85   193.2   18.4       65.7   15.2
88    88.3   25.5       73.4   12.9
90   134.3    4.9        9.3   11.2
91    28.6    1.5       33.0    7.3
99   135.2   41.7       45.9   17.2
103  187.9   17.2       17.9   14.7
112  175.7   15.4        2.4   14.1
122  224.0    2.4       15.6   11.6
130    0.7   39.6        8.7    1.6
132    8.4   27.2        2.1    5.7
148   38.0   40.3       11.9   10.9
150  280.7   13.9       37.0   16.1
152  197.6   23.3       14.2   16.6
153  171.3   39.7       37.7   19.0
154  187.8   21.1        9.5   15.6
155    4.1   11.6        5.7    3.2
161   85.7   35.8       49.3   13.3
167  206.8    5.2       19.4   12.2
173  168.4    7.1       12.8   11.7
186  139.5    2.1       26.6   10.3
187  191.1   28.7       18.2   17.3
191   75.5   10.8        6.0    9.9
195   38.2    3.7       13.8    7.6
197  177.0    9.3        6.4   12.8